config/routes.rb
Rails.application.routes.draw do
  root 'products#index'
  resources :products do
    resources :reviews, only: [:create, :destroy]
  end

  resources :users, only: [:new, :create]

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

end

app/models/department.rb
class Department < ActiveRecord::Base

  has_many :departmentalizations, dependent: :destroy
  has_many :products, through: :departmentalizations

  validates :name, presence: true, uniqueness: true 

end

app/models/departmentalization.rb
class Departmentalization < ActiveRecord::Base
  belongs_to :department
  belongs_to :product

  validates_associated :department, :product
  validates :department_id, uniqueness: { scope: :product }

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :reviews, dependent: :destroy

  has_many :departmentalizations, dependent: :destroy
  has_many :departments, through: :departmentalizations

  validates :name, presence: true, length: { minimum: 3 }
  validates :description, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }

  before_create :case_format

    private

      def case_format
        self.description = self.description.humanize
        self.name = self.name.titleize
      end

end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :product
  validates :body, presence: true, uniqueness: { scope: :product_id}, length: { minimum: 3 }

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  VALID_EMAIL_REGEX = /\A([\w+\-]\.?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true,
            uniqueness: true,
            format: VALID_EMAIL_REGEX
  validates :password, length: { minimum: 5 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def sign_in(user)
    session[:user_id] = user.id
  end

  def user_signed_in?
    session[:user_id].present?
  end
  helper_method :user_signed_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if user_signed_in?
  end
  helper_method :current_user

  def emojify(content)
   h(content).to_str.gsub(/:([\w+-]+):/) do |match|
     if emoji = Emoji.find_by_alias($1)
       %(<img alt="#$1" src="#{image_path("emoji/#{emoji.image_filename}")}" style="vertical-align:middle" width="20" height="20" />)
     else
       match
     end
   end.html_safe if content.present?
 end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :find_product, only: [:show, :update, :edit, :destroy]

  def index
    # @products = Product.all
    @products = Product.order("price ASC").page(params[:page]).per(25)
    # respond_to do |format|
    #   format.html
    #   format.json { render json: @products }
    # end
  end

  def new
    @product = Product.new
  end

  def create
    # product_params = params.require(:product).permit([:name, :description, :price])
    # puts product_params
    @product = Product.new(product_params)
    if @product.save
      flash[:success] = "Sounds like a real seller..."
      redirect_to product_path(@product)
    else
      render :new
    end
  end

  def show
    @review = Review.new
    # @product = Product.find(params[:id])
  end

  def edit
    # @product = Product.find(params[:id])
  end

  def update
    # @product = Product.find(params[:id])
    # product_params = params.require(:product).permit([:name, :description, :price])
    if @product.update(product_params)
      redirect_to(product_path(@product), flash: { success: "product updated" })
    else
      render :edit
    end
  end

  def destroy
    # product = Product.find(params[:id])
    @product.destroy
    redirect_to(root_path, flash: { danger: "product deleted" })
  end

  private

    def product_params
      params.require(:product).permit([:name, :description, :price,
                                            { department_ids: [] }])
    end

    def find_product
      @product = Product.find(params[:id])
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def create
    @product = Product.find(params[:product_id]) #found through routes params
    # @review = Review.new(review_params) # just instanstiated
    @review = Review.new(review_params)
    @review.product = @product
    # @review.product_id = @product.id #this sets the foreign_key on the review to be associated with the product
    # @review = Product.find(params[:product_id]).review.new(review_params)
    respond_to do |format|
      if @review.save
        format.html { redirect_to product_path((@product), flash: { success: "Review created successfully"}) }
        format.js { render :create_success }
        # at a given request only a single one of these will execute
      else
        # can just render the template associated here...but how does it find the id? we already have the id
        format.html { render "products/show" }
        format.js { render :create_failure }
        # render json: params
      end
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    # we can redirect back to the product path because our resources are in the URL and are accessible.
    respond_to do |format|
      format.html { redirect_to product_path(params[:product_id]), flash: { danger: "Answer Deleted." } }
      format.js { render }
    end
  end

    private

      def review_params
        params.require(:review).permit([:body])
      end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      sign_in(user)
      redirect_to root_path, flash: { success: "Signed in..." }
    else
      flash[:danger] = "Email/Password combination not valid..."
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, flash: { warning: "Successfully Logged Out!" }
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      # session simply checks for the user.ID in the current session?
      # session[:user_id] = @user.id
      sign_in(@user)
      redirect_to root_path, notice: "User Created!"
    else
      render :new
    end
  end

    private

      def user_params
        params.require(:user).permit([:first_name, :last_name, :email, :password, :password_confirmation])
      end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Amazon</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
</head>
<body>
  <nav class="navbar navbar-full navbar-dark" style="background-color: rgba(252, 184, 95, 0.92)">

      <div class="container">
      <%= link_to root_path do %>
        <i class="fa fa-amazon fa-3x"></i>
      <% end %>

  <i class="fa-4x fa-unicorn">🦄</i>
      <h3 class = "<%= 'active' if current_page?(root_path)%>">
        <strong><%= link_to "Nozama", root_path, class: "nav-link brand-homepage" %></strong>
      </h3>

      <button class="navbar-toggler hidden-md-up" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar2"> &#9776; </button>
      <div class="collapse navbar-toggleable-sm" id="exCollapsingNavbar2">

          <ul class="nav navbar-nav">
            <li class="nav-item">

            </li>
            <% if user_signed_in? %>
            <li class="nav-item <%= 'active' if current_page?(new_product_path)%>">
              <%= link_to "Add a New Product", new_product_path, class: "nav-link" %>
            </li>

            <li class="nav-item <%= 'active' if current_page?(root_path) %>">
              <%= link_to "Log out", sessions_path, method: :delete, class: "nav-link" %>
            </li>

            <% else %>
              <li class="nav-item <%= 'active' if current_page?(new_user_path) %>">
                <%= link_to "Sign Up", new_user_path, class: "nav-link" %>
              </li>
              <li class="nav-item <%= 'active' if current_page?(new_session_path) %>">
                <%= link_to "Sign In", new_session_path, class: "nav-link" %>
              </li>
            <% end %>
          </ul>
      </div>
    </div>
  </nav>

  <% if flash %>
    <section class="container ">
      <% flash.each do | message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end  %>
    </section>
  <% end %>

<%# if user_signed_in? %>
  <!-- Hello <%# current_user.first_name %> -->
  <%# link_to "Log out", sessions_path, method: :delete %>
<%# else %>
  <%# link_to "Sign Up", new_user_path %>
  <!-- or <%# link_to "Sign In", new_session_path %> -->
<%# end %>

<main class="container">
  <%= yield %>
</main>

<script src="jquery.matchHeight.js" type="text/javascript"></script>
</body>
</html>

app/views/products/_form.html.erb
<% if @product.errors.any? %>
<div class="row">
  <div class="col-md-6 col-md-offset-3 alert alert-danger">
    <p>The form contains <strong><%= pluralize(@product.errors.count, "error") %></strong>.</p>
  <ul>
    <% @product.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
  </div>
</div>
<% end %>

<!-- <div class="field_with_errors"> -->
<!-- <%= @product.errors.full_messages.join(" - ") %> -->
<!-- </div> -->
<div class="row">
  <div class="form-group-lg col-md-6 col-md-offset-3">
    <%= form_for @product do |f| %>
      <div class = "form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      <div class = "form-group">
        <%= f.label :description %>
        <%= f.text_area :description, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%# the attribute we are working with the order, what it posts to the server, what it displays %>
      <%= f.collection_check_boxes(:department_ids, Department.order("name"), :id, :name) %>
      </div>
      <div class = "form-group">
        <%= f.label :price %>
        <%= f.text_field :price,
          :value => (number_with_precision(f.object.price, :precision => 2) || 0), class: 'form-control' %>
      </div>
      <div class = "form-group">
        <%= f.submit "Create Product", class: "btn btn-primary-outline btn-block" %>
      </div>
  <% end %>
  </div>
</div>

app/views/products/edit.html.erb
<h1 class = "text-lg-center title">Edit Product</h1>

<%= render "form" %>

app/views/products/index.html.erb
<h1 class = "title text-lg-center">All Products (<%= @products.length %>) </h1>
<!-- List All Products -->
<article class="row">
  <section class="list-products">
    <% @products.each do |product| %>
      <section class="col-md-4 col-sm-4 col-xs-product item">
        <h4><%= link_to product.name, product_path({id: product.id}) %></h4>
            <strong><%= number_to_currency(product.price) %></strong>
            <span class="emo-prod"><%= Emoji.find_by_alias("lemon").raw %></span>
            <p><%= product.description %></p>
        </section>
    <% end %>
  </section>
</article>
<article class="row">
  <section class="text-lg-center">
    <%= paginate @products %>
  </section>
</article>
<script>
$(function() {
  $('.item').matchHeight();
});
</script>

app/views/products/new.html.erb
<h2 class = "text-lg-center title">Create A New Product</h2>
<%= render "form" %>

app/views/products/show.html.erb
<!-- LIST PRODUCT -->
<div class="row">
  <div class="product-display form-group-lg col-md-6 col-md-offset-3">
  <h1><%= @product.name %> <span class="prod-cost"><%= number_to_currency(@product.price) %></span></h1>
  <h5><%= @product.description %></h5>
  <p class = "text-muted"><%= link_to "EDIT", edit_product_path(@product) %></p>
  <p class = "text-muted"><%= link_to "DELETE", product_path(@product), method: :delete, data: { confirm: "Are you sure??"} %></p>
  </div>
</div>

<div id="review_form">
  <%= render "/reviews/form" %>
</div>


<!-- DISPLAY ALL THE REVIEWS -->
<div class="row">
  <div class="form-group-lg col-md-6 col-md-offset-3">
    <h2 class= "text-lg-center">Reviews:</h2>
    <div class="listed-reviews">
      <!-- <%= render @product.reviews %> -->
      <%# the above is a magical way of accomplishing the below %>
      <% @product.reviews.each do |review| %>
        <%= render "reviews/review", review: review %>
      <% end %>
    </div>
  </div>
</div>

app/views/reviews/_form.html.erb
<h3 class = "text-lg-center">Add a review: </h3>
    <!-- DISPLAYS THE ERROR FOR REVIEWS -->
    <% if @review.errors.any? %>
      <div class="row">
        <div class="form-group-lg col-md-6 col-md-offset-3 alert alert-danger">
          <p>The form contains <strong><%= pluralize(@review.errors.count, "error") %></strong>.</p>
          <ul>
            <% @review.errors.full_messages.each do |error| %>
              <li><%= error %></li>
            <% end %>
          </ul>
        </div>
      </div>
    <% end %>
  <!-- CREATE NEW REVIEWS -->
<section class="row">
  <section class="form-group-lg col-md-6 col-md-offset-3">
<%# this remote true: is using $("form[data-remote='true']").on("submit", function(e) {e.preventDefault()}); Just preventing defualt submit action along with a data-remote true attribute %>
    <%= form_for [@product, @review], remote: true do |f|  %>
      <div class = "form-group">
        <%# f.label :body %>
        <%= f.text_area :body, class: "form-control" %>
      </div>
      <div class = "form-group">
          <%= f.submit "Create Review", class: "btn btn-primary-outline btn-block" %>
      </div>
    <% end %>
  </section>
</section>

app/views/reviews/_review.html.erb
<li id = "<%= dom_id(review) %>">
  <%= review.body %>
  <%= link_to "Delete", product_review_path(@product, review),
                        method: :delete,
                        remote: true,
                        data: { confirm: "Are you sure?!" } %>
</li>

app/views/reviews/create_failure.js.erb
$("#review_form").html("<%= j render 'form' %>")

app/views/reviews/create_success.js.erb
$('.listed-reviews').prepend("<%= j render 'review', review: @review %>");
<% @review = Review.new %>
$("#review_form").html("<%= j render 'form' %>")
$("#review_body").val("");

app/views/reviews/destroy.js.erb
$("#<%= dom_id(@review) %>").fadeOut(2000, function() {
  $(this).remove();
});

app/views/users/new.html.erb
<h1 class = "text-lg-center title">Create an Account</h1>

  <% if @user.errors.any? %>
  <div class="row">
    <div class="col-md-6 col-md-offset-3 alert alert-danger">
      <p>The form contains <strong><%= pluralize(@user.errors.count, "error") %></strong>.</p>
    <ul>
      <% @user.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
    </div>
  </div>
  <% end %>

<div class="row">
  <div class="form-group-lg col-md-6 col-md-offset-3">
  <%= form_for @user do |f| %>
    <div class = "form-group">
      <%= f.label :first_name %>
      <%= f.text_field :first_name, class: 'form-control' %>
    </div>
    <div class = "form-group">
      <%= f.label :last_name %>
      <%= f.text_field :last_name, class: 'form-control' %>
    </div>
  <div class = "form-group">
      <%= f.label :email  %>
      <%= f.email_field :email, class: 'form-control' %>
    </div>
    <div class = "form-group">
      <%= f.label :password  %>
      <%= f.password_field :password, class: 'form-control' %>
    </div>
    <div class = "form-group">
      <%= f.label :password_confirmation  %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
    </div>
    <div class = "form-group">
      <%= f.submit "Create Account", class: "btn btn-primary-outline btn-block" %>
    </div>
  <% end %>
  </div>
</div>